config/routes.rb
Rails.application.routes.draw do
  
  root to: 'admin/documents#index'
 

  devise_for :user, path: 'admin', controllers: {
    registrations: 'admin/registrations'
  }
  namespace :admin do
    resources :users
    resources :reports
    get '/search-report', to: 'documents#index', as: :search_report
    get 'download_xls_report', to: 'documents#download_xls',  as: :download_xls_report
    get 'download_export_excel', to: 'documents#export_excel',  as: :download_export_excel
    
    get 'edit_password', to: 'users#edit_password',  as: :edit_password
    patch 'update_password', to: 'users#update_password',  as: :update_password
    
    
    resources :documents, only: [:upload] do
      collection do
        post :upload
      end 
      
    end 
   
    root to: 'documents#index' 
  end 

  
  
end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < Admin::ApplicationController
  require 'rubyXL'
  def index
    @reports = Report.where(user_id: current_user.id).paginate(page: params[:page], per_page: 5)
    if params[:search].present?
      if params[:search].present?
        search_params = params[:search]
        search_params.each do |key, value|
          case key
          when 'numero'
            @reports = @reports.where(numero: value).paginate(page: params[:page], per_page: 5) if value.present?
          when 'serie'
            @reports = @reports.where(serie: value).paginate(page: params[:page], per_page: 5) if value.present?
          when 'fantasia_emitente'
            @reports = @reports.where(fantasia_emitente: value).paginate(page: params[:page], per_page: 5) if value.present?
          when 'nome_destinatario'
            @reports = @reports.where(nome_destinatario: value).paginate(page: params[:page], per_page: 5) if value.present?
          when 'cnpj_emitente'
            @reports = @reports.where(cnpj_emitente: value).paginate(page: params[:page], per_page: 5) if value.present?
          when 'cnpj_destinatario'
            @reports = @reports.where(cnpj_destinatario: value).paginate(page: params[:page], per_page: 5) if value.present?
          end
        end
      end
    end
  end 
  
  def upload
    
    if params[:file].present?
      uploaded_file = params[:file] 
      if uploaded_file.content_type == "text/xml"
        file_path = Rails.root.join('tmp', uploaded_file.original_filename)
        File.open(file_path, 'wb') { |file| file.write(uploaded_file.read) }
        XmlProcessorWorker.perform_async(file_path, current_user.id)
        flash[:notice] = "XML file sent successfully! Processing will be done in the background."
      else
        flash[:alert] = "Please submit a valid XML file."
      end  
      redirect_to admin_root_path(flag: true)
    elsif params[:zip].present?
      file = params[:zip]
      Dir.mktmpdir do |dir|
        Zip::File.open(file.path) do |zip_file|
          zip_file.each do |entry|
            next unless entry.name.end_with?('.xml')
            extracted_file_path = Rails.root.join('tmp', entry.name)
            entry.extract(extracted_file_path) { true } 
            XmlProcessorWorker.perform_async(extracted_file_path.to_s, current_user.id)
          end 
        end
      end  
      flash[:notice] = "File sent successfully! Processing will be done in the background."
      redirect_to admin_root_path(flag: true)
    else
     flash[:alert] = "Forbidden empty field."
     redirect_to admin_root_path
    end 
  end 



  def download_xls
    @report = Report.find(params[:id])
    workbook = RubyXL::Workbook.new
    worksheet = workbook[0]

  
    worksheet.add_cell(0, 0, 'Dados do Documento Fiscal')
    worksheet.add_cell(1, 0, 'Número da Série')
    worksheet.add_cell(1, 1, @report.serie)
    worksheet.add_cell(2, 0, 'Número da Nota Fiscal')
    worksheet.add_cell(2, 1, @report.numero)
    worksheet.add_cell(3, 0, 'Data e Hora de Emissão')
    worksheet.add_cell(3, 1, @report.data_emissao.strftime("%d/%m/%Y %H:%M"))

  
    worksheet.add_cell(5, 0, 'Dados do Emitente')
    worksheet.add_cell(6, 0, 'CNPJ')
    worksheet.add_cell(6, 1, @report.cnpj_emitente)
    worksheet.add_cell(7, 0, 'Nome')
    worksheet.add_cell(7, 1, @report.nome_emitente)
    worksheet.add_cell(8, 0, 'Fantasia')
    worksheet.add_cell(8, 1, @report.fantasia_emitente)
    worksheet.add_cell(9, 0, 'Endereço')
    worksheet.add_cell(9, 1, @report.endereco_emitente)

    
    worksheet.add_cell(11, 0, 'Dados do Destinatário')
    worksheet.add_cell(12, 0, 'CNPJ')
    worksheet.add_cell(12, 1, @report.cnpj_destinatario)
    worksheet.add_cell(13, 0, 'Nome')
    worksheet.add_cell(13, 1, @report.nome_destinatario)
    worksheet.add_cell(14, 0, 'Endereço')
    worksheet.add_cell(14, 1, @report.endereco_destinatario)

 
    worksheet.add_cell(16, 0, 'Produtos')
    @report.products.each_with_index do |produto, index|
      base_row = 17 + (index * 9) 
      worksheet.add_cell(base_row, 0, "Produto #{index + 1}:")
      worksheet.add_cell(base_row + 1, 0, 'Nome')
      worksheet.add_cell(base_row + 1, 1, produto["produto"]["nome"])
      worksheet.add_cell(base_row + 2, 0, 'NCM')
      worksheet.add_cell(base_row + 2, 1, produto["produto"]["NCM"])
      worksheet.add_cell(base_row + 3, 0, 'CFOP')
      worksheet.add_cell(base_row + 3, 1, produto["produto"]["CFOP"])
      worksheet.add_cell(base_row + 4, 0, 'Unidade Comercializada')
      worksheet.add_cell(base_row + 4, 1, produto["produto"]["uCom"])
      worksheet.add_cell(base_row + 5, 0, 'Quantidade Comercializada')
      worksheet.add_cell(base_row + 5, 1, produto["produto"]["qCom"].to_s)
      worksheet.add_cell(base_row + 6, 0, 'Valor Unitário')
      worksheet.add_cell(base_row + 6, 1, produto["produto"]["vUnCom"].to_s)
      worksheet.add_cell(base_row + 7, 0, 'ICMS')
      worksheet.add_cell(base_row + 7, 1, produto["impostos"]["vICMS"].to_s)
      worksheet.add_cell(base_row + 8, 0, 'IPI')
      worksheet.add_cell(base_row + 8, 1, produto["impostos"]["vIPI"].to_s)
      worksheet.add_cell(base_row + 9, 0, 'PIS')
      worksheet.add_cell(base_row + 9, 1, produto["impostos"]["vPIS"].to_s)
      worksheet.add_cell(base_row + 10, 0, 'COFINS')
      worksheet.add_cell(base_row + 10, 1, produto["impostos"]["vCOFINS"].to_s)
    end

    
    totalizadores_row = 17 + (@report.products.size * 9) + 2
    worksheet.add_cell(totalizadores_row, 0, 'Totalizadores')
    worksheet.add_cell(totalizadores_row + 1, 0, 'Valor Total dos Produtos')
    worksheet.add_cell(totalizadores_row + 1, 1, "R$ #{@report.valor_total_produtos}")
    worksheet.add_cell(totalizadores_row + 2, 0, 'Valor Total do ICMS')
    worksheet.add_cell(totalizadores_row + 2, 1, "R$ #{@report.valor_total_icms}")
    worksheet.add_cell(totalizadores_row + 3, 0, 'Valor Total do IPI')
    worksheet.add_cell(totalizadores_row + 3, 1, "R$ #{@report.valor_total_ipi}")
    worksheet.add_cell(totalizadores_row + 4, 0, 'Valor Total do PIS')
    worksheet.add_cell(totalizadores_row + 4, 1, "R$ #{@report.valor_total_pis}")
    worksheet.add_cell(totalizadores_row + 5, 0, 'Valor Total do COFINS')
    worksheet.add_cell(totalizadores_row + 5, 1, "R$ #{@report.valor_total_cofins}")
    worksheet.add_cell(totalizadores_row + 6, 0, 'Valor Total da Nota Fiscal')
    worksheet.add_cell(totalizadores_row + 6, 1, "R$ #{@report.valor_total_nota_fiscal}")

    
    temp_file = Tempfile.new(['relatorio', '.xlsx'])
    workbook.write(temp_file.path)

    
    send_file temp_file.path, filename: "nfe_numero_#{@report.numero}.xlsx", type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  end 

  def export_excel
    @reports = Report.order(params[:sort])

    workbook = RubyXL::Workbook.new
    worksheet = workbook[0]
    worksheet.sheet_name = 'Relatórios'
    
    headers = ['Número', 'Série', 'Emitente', 'Destinatário', 'CNPJ Emitente', 'CNPJ Destinatário']
    headers.each_with_index do |header, index|
      worksheet.add_cell(0, index, header)
    end
  
    @reports.each_with_index do |report, index|
      worksheet.add_cell(index + 1, 0, report.numero)
      worksheet.add_cell(index + 1, 1, report.serie)
      worksheet.add_cell(index + 1, 2, report.fantasia_emitente)
      worksheet.add_cell(index + 1, 3, report.nome_destinatario)
      worksheet.add_cell(index + 1, 4, report.cnpj_emitente)
      worksheet.add_cell(index + 1, 5, report.cnpj_destinatario)
    end

    temp_file = Tempfile.new(['relatorios', '.xlsx'])
    workbook.write(temp_file.path)
    send_file temp_file.path, filename: "relatorios_#{Date.today}.xlsx", type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  end
  

end

app/views/admin/documents/index.html.slim
h2.text-center Dashboard

= form_with url: upload_admin_documents_path, local: true, html: { multipart: true, :class => 'form-horizontal'} do |form|
  section.panel.panel-default.dashboard
    .panel-body
      label = "XML"   
      = form.file_field :file, accept: 'application/xml'
    .panel-body 
      label = "Zip com XML's" 
      = form.file_field :zip, accept: '.zip'
    .panel-body 
        span.h3.block.m-t-xs.text-success= @reports_count
        small.text-muted.text-u-c XML's
        span.i-s.i-s-2x.pull-left.m-r-sm
          .text-success
            = icon('fas', 'book')
    .panel-body
      span.clear
        span.h3.block.m-t-xs.text-success= "Listagem"
        small.text-muted.text-u-c Excel
      = link_to admin_download_export_excel_path, class: "btn btn-success" do 
        = icon('fas', 'download')
  = form.submit "Enviar", class: "btn-primary"


- if @reports.present?    
  h2.text-center Relatórios
  .panel.panel-default 
    .panel-body
      = simple_form_for :search, url: admin_search_report_path, html: {class: 'search-form'}, method: :get do |f|
        .row
          .col-md-3
            = f.label :numero, label: 'Número', required: false
            = f.input_field :numero, class: 'col-md-12 form-control'
          .col-md-3
            = f.label :serie, label: 'Série', required: false
            = f.input_field :serie, class: 'col-md-12 form-control'
          .col-md-3
            = f.label :fantasia_emitente, label: 'Emitente', required: false
            = f.input_field :fantasia_emitente, class: 'col-md-12 form-control'
          .col-md-3
            = f.label :nome_destinatario, label: 'Destinatário', required: false
            = f.input_field :nome_destinatario, class: 'col-md-12 form-control' 
          .col-md-3
            = f.label :cnpj_emitente, label: 'CNPJ Emitente', required: false
            = f.input_field :cnpj_emitente, class: 'col-md-12 form-control' 
          .col-md-3
            = f.label :cnpj_destinatario, label: 'CNPJ Destinatário', required: false
            = f.input_field :cnpj_destinatario, class: 'col-md-12 form-control'
          .col-md-1.mt-25
            = f.submit 'Buscar', class: 'btn btn-primary'
          .col-md-1.mt-25
            = link_to 'Limpar Busca', admin_root_path, class: 'btn btn-warning' 
  .panel.panel-default 
    .table-responsive
      table.table.table-striped.b-t.b-light
        thead
          tr
            th.text-center = link_to " ⇧⇩ | Número", admin_root_path(sort: :numero)   
            th.text-center = link_to "⇧⇩ | Série" , admin_root_path(sort: :serie) 
            th.text-center = link_to "A-Z ⇧⇩ | Emitente " , admin_root_path(sort: :fantasia_emitente)
            th.text-center = link_to "A-Z ⇧⇩ | Destinatário", admin_root_path(sort: :nome_destinatario)
            th.text-center = link_to "⇧⇩ | CNPJ Emitente" , admin_root_path(sort: :cnpj_emitente)
            th.text-center = link_to "⇧⇩ | CNPJ Destinatário", admin_root_path(sort: :cnpj_destinatario)
            th.text-center(width=210) Ações
        tbody   
          - @reports.order(params[:sort]).each do |r|
            tr
              td.text-center= r.numero
              td.text-center= r.serie 
              td.text-center= r.fantasia_emitente
              td.text-center= r.nome_destinatario
              td.text-center= r.cnpj_emitente
              td.text-center= r.cnpj_destinatario
              td.text-center.links-actions
                = link_to admin_report_path(r), class: "btn btn-info", title: 'Visualizar Relatório', data: { toggle: 'tooltip'} do
                  = icon('far', 'eye') 
                = link_to  admin_report_path(r), method: :delete, class: "btn btn-danger", title: 'Apagar', data: { confirm: 'Tem Certeza?', toggle: 'tooltip' } do
                  = icon('far', 'trash-alt')
                = link_to admin_download_xls_report_path(id: r.id), class: "btn btn-success" do 
                 = icon('fas', 'download')
    .text-center
      = will_paginate(@reports, renderer: 'ApplicationHelper::LinkRenderer', class: 'pagination pagination-lg')