config/routes.rb
Rails.application.routes.draw do
  
  root to: 'admin/documents#index'
 

  devise_for :user, path: 'admin', controllers: {
    registrations: 'admin/registrations'
  }
  namespace :admin do
    resources :users
    resources :reports
    get '/search-report', to: 'documents#index', as: :search_report
    get 'download_xls_report', to: 'documents#download_xls',  as: :download_xls_report
    get 'download_export_excel', to: 'documents#export_excel',  as: :download_export_excel
    
    get 'edit_password', to: 'users#edit_password',  as: :edit_password
    patch 'update_password', to: 'users#update_password',  as: :update_password
    
    
    resources :documents, only: [:upload] do
      collection do
        post :upload
      end 
      
    end 
   
    root to: 'documents#index' 
  end 

  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ResourceController
  def edit_password
    @user = current_user
  end

  def update_password
    @user = User.find(current_user.id)
    if @user.update(user_params)
      sign_in @user, :bypass => true
      redirect_to admin_root_path
    else
      render :edit_password
    end
  end 

  private
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/admin/users/edit.html.slim
h2 Usuário
= simple_form_for [:admin, resource], :html => { :class => 'form-horizontal' } do |f|
  section.panel.panel-default
    header.panel-heading.font-bold
      = resource.new_record? ? "Adicionar Usuário" : "Editar Usuário #{resource.email}"
    .panel-body  
      = f.input :email, :label => 'E-mail'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :password, :label => 'Senha'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :password_confirmation, :label => 'Repita a Senha'
     

  = render 'admin/shared/form_actions', f: f

app/views/admin/users/edit_password.html.slim
h2 Editar Senha
= simple_form_for @user, url: admin_update_password_path, :html => { :class => 'form-horizontal' } do |f|
  section.panel.panel-default
    header.panel-heading.font-bold
      | Editar Senha
    .panel-body  
      = f.input :password, :label => "Nova senha", :required => true, :autofocus => true
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :password_confirmation, :label => "Confirme sua nova senha", :required => true
      = f.button :submit, 'Salvar', :class => 'btn btn-primary'

app/views/admin/users/index.html.slim
h2 Usuários
.panel.panel-default
  .table-responsive
    table.table.table-striped.b-t.b-light
      thead
        tr
          th.text-center E-mail
          th.text-center(width=210) Ações
      tbody    
        - collection.each do |r|
          tr
            td.text-center= r.email
            td.text-center.links-actions
              = render 'admin/shared/actions', r: r
= render 'admin/shared/create'

app/views/admin/users/new.html.slim
h2 Usuário
= simple_form_for [:admin, resource], :html => { :class => 'form-horizontal' } do |f|
  section.panel.panel-default
    header.panel-heading.font-bold
      = resource.new_record? ? "Adicionar Usuário" : "Editar Usuário #{resource.email}"
    .panel-body  
      = f.input :email, :label => 'E-mail'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :password, :label => 'Senha'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :password_confirmation, :label => 'Repita a Senha'
     

  = render 'admin/shared/form_actions', f: f