config/routes.rb
Rails.application.routes.draw do
  
  root to: 'admin/documents#index'
 

  devise_for :user, path: 'admin', controllers: {
    registrations: 'admin/registrations'
  }
  namespace :admin do
    resources :users
    resources :reports
    get '/search-report', to: 'documents#index', as: :search_report
    get 'download_xls_report', to: 'documents#download_xls',  as: :download_xls_report
    get 'download_export_excel', to: 'documents#export_excel',  as: :download_export_excel
    
    get 'edit_password', to: 'users#edit_password',  as: :edit_password
    patch 'update_password', to: 'users#update_password',  as: :update_password
    
    
    resources :documents, only: [:upload] do
      collection do
        post :upload
      end 
      
    end 
   
    root to: 'documents#index' 
  end 

  
  
end

app/views/layouts/admin.html.slim
doctype html
html lang="pt-BR"
  head
    meta charset="utf-8"
    meta name="robots" content="noindex"
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    title= content_for?(:title) ? yield(:title) : "Easy XML 1.0"

    = stylesheet_link_tag "admin/application", media: "all"
    = javascript_include_tag "admin/application"

    = csrf_meta_tags

  body
    section.vbox
      header.bg-white.header.header-md.navbar.navbar-fixed-top-xs.box-shadow
        - flash.each do |name, msg|
          p(class="#{name}")= msg         
        .navbar-header.aside-md.dk
          a.btn.btn-link.visible-xs data-target="#nav,html" data-toggle="class:nav-off-screen,open"
            = icon('far', 'bars')
          = link_to admin_root_path, class: 'navbar-brand' do
            p EasyXml
          a.btn.btn-link.visible-xs data-target=".user" data-toggle="dropdown"
            i.fa.fa-cog
        ul.nav.navbar-nav.navbar-right.m-n.hidden-xs.nav-user.user

          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"

              - if user_signed_in?
                = current_user.email
              b.caret
            - if user_signed_in?
              ul.dropdown-menu.animated.fadeInRight
                li
                  = link_to "Logout", destroy_user_session_path, :method => :delete, :data => { :toggle => "ajaxModal"}
                - if current_user.email != "desenvolvimento@easy.xml"
                  li
                    = link_to "Editar Senha", admin_edit_password_path
                
      section
        section.hbox.stretch
          /! .aside
          aside#nav.bg-black.aside-md.hidden-print.hidden-xs
            section.vbox
              section.w-f.scrollable
                .slim-scroll data-disable-fade-out="true" data-distance="0" data-height="auto" data-railopacity="0.2" data-size="10px"
                  nav.nav-primary.hidden-xs
                    .text-muted.text-sm.hidden-nav-xs.padder.m-t-sm.m-b-sm 
                    ul.nav.nav-main data-ride="collapse"
                      = nav_link_to admin_root_path, {:class => 'menu_link'}, {:wrapper => 'li', :wrapper_class => 'item_menu', :selected_class => 'active'} do
                        = icon('fas', 'tachometer-alt')
                        span.font-bold Dashboard

                      - unless current_user.email != "desenvolvimento@easy.xml"
                        = nav_link_to admin_users_path, {:class => 'menu_link'}, {:wrapper => 'li', :wrapper_class => 'item_menu', :selected_class => 'active', :url_segment => 2 }
                          = icon('far', 'user')
                          span.font-bold Usuários

                                                   
                footer.footer.hidden-xs.no-padder.text-center-nav-xs
                  a.btn.btn-icon.icon-muted.btn-inactive.m-l-xs.m-r-xs data-toggle="class:nav-xs" href="#nav"
                    .text
                      = icon('fas', 'reply')
                    .text-active
                      = icon('fas', 'share')
          section#content
            section.hbox.stretch
              section
                section.vbox
                  section.scrollable.padder
                    section.row.m-b-md
                      .col-md-12
                        = yield
            footer
              .container
                .col-sm-6.col-sm-offset-3
                  .pull-left
                    | &copy; #{Date.today.year} | Todos os direitos reservados.
                  .pull-right
                    | v #{EasyXml::Application.config.version}

app/views/layouts/devise.html.slim
doctype html
html.html-devise lang="pt-BR"
  head
    meta charset="utf-8"
    meta name="keywords" content=""
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"

    title= "Easy XML 1.0"

    = stylesheet_link_tag "admin/application", media: "all"
    = javascript_include_tag "admin/application"

    = csrf_meta_tags

  body
    section#content.wrapper-md.animated.fadeInUp
      .container.aside-xl
        .user-img.block = image_tag 'logo_easy_xml.png'
        section.m-b-md
          = yield
        
     
        
        

          
          